This package tries to ease the workflow of local development, compilation on remote machines, and fixing errors locally with =next-error= .

It rsync's ("ping") current project to a remote machine, then compiles ("pong") there and convert remote paths in the compilation output to local paths, so that =compilation-mode= can find files correctly.

* Dependencies

- built-in packages: compile, auth-source, project
- rsync
- ssh
- expect

Only tested with GNU Emacs 26.1 on Linux.

* How to use

=M-x ppcompile= to rsync and compile the current project, sometimes you may just want to rsync files, then prefix the command, i.e. =M-u M-x ppcompile= .

You need to have below settings, globally or per project:
- =ppcompile-ssh-host= :: the remote host
- =ppcompile-ssh-port= :: the ssh port of remote host, defaults to 22
- =ppcompile-ssh-user= :: user name, which defaults to currently logged in user, as returned by =(user-login-name)=
- =ppcompile-rsync-dst-dir= :: remote containing directory for the project
- =ppcompile-remote-compile-command= :: compile command on the remote host
- =ppcompile-path-mapping-list= :: alist for path mapping
  =car= is a remote path and =cdr= a local path for each element, all paths should be absolute paths.

You may consider putting these in =.dir-locals.el= if you have more than 1 remote hosts.
There is an example of [[https://github.com/whatacold/ppcompile-test-project/blob/master/.dir-locals.el][.dir-locals.el]] example in the test project.

Chances are that you may want to debug your settings, do it with =M-x ppcompile-toggle-debug=.

Besides that, you need to configure your password in some =auth-source= backends, for example, =~/.authinfo= :
#+BEGIN_SRC
machine localhost port 22 login try password 1
#+END_SRC

Also pay attention to Emacs variable =auth-sources= to include your setting.

The project root is detected via =(project-current)= , if it fails =ppcompile= will take the top-level `git` directory as project root.
* Final words

This is my first time to roll out a package seriously, I believe there is much to improve,
pull requests or issues are very welcome.

Some TODOs:
- [ ] Add tests
- [ ] Improve README and code
- [ ] Try to remove the dependency on =expect=